### PR TITLE
Upgrade php min version.

### PR DESCRIPTION
**Pull request by sia-simeonova**

### CODE REVIEW

**Comment by ronangr1** [comment]
@sia-simeonova Hello, please ask for a review now

**Comment by sia-simeonova** [comment]
> @sia-simeonova Hello, please ask for a review now

Hi, @ronangr1 , you are assigned as an reviewer, should I do anything else? Thank you.

**Review by ronangr1 — COMMENTED** [review]
Hello @sia-simeonova 

There are many many files commited. Would you please check if all of theses files are required to upgrade the php version ?

The vendor folder needs to be added to the repo ?

Thanks

**Comment by sia-simeonova** [comment]
> Hello @sia-simeonova
> 
> There are many many files commited. Would you please check if all of theses files are required to upgrade the php version ?
> 
> The vendor folder needs to be added to the repo ?
> 
> Thanks

Hi, @ronangr1, yes it's made that way from the beginning of the implementation so the user is not required to execute composer install.

**Review by ronangr1 — APPROVED** [review]

**Pull request merged**
